name: Publish

on:
  workflow_dispatch: 
  push:
    branches:
    - mainm
    
jobs: 
  publish: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: action/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./ShopStore.sln
      
      - name: Build
        run: dotnet build ./ShopStore.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./ShopStore.sln --configuration Release --no-build
